// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feature.proto

package stormtf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Containers to hold repeated fundamental values.
type BytesList struct {
	Value                [][]byte `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesList) Reset()         { *m = BytesList{} }
func (m *BytesList) String() string { return proto.CompactTextString(m) }
func (*BytesList) ProtoMessage()    {}
func (*BytesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{0}
}
func (m *BytesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesList.Unmarshal(m, b)
}
func (m *BytesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesList.Marshal(b, m, deterministic)
}
func (dst *BytesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesList.Merge(dst, src)
}
func (m *BytesList) XXX_Size() int {
	return xxx_messageInfo_BytesList.Size(m)
}
func (m *BytesList) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesList.DiscardUnknown(m)
}

var xxx_messageInfo_BytesList proto.InternalMessageInfo

func (m *BytesList) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type FloatList struct {
	Value                []float32 `protobuf:"fixed32,1,rep,packed,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FloatList) Reset()         { *m = FloatList{} }
func (m *FloatList) String() string { return proto.CompactTextString(m) }
func (*FloatList) ProtoMessage()    {}
func (*FloatList) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{1}
}
func (m *FloatList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatList.Unmarshal(m, b)
}
func (m *FloatList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatList.Marshal(b, m, deterministic)
}
func (dst *FloatList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatList.Merge(dst, src)
}
func (m *FloatList) XXX_Size() int {
	return xxx_messageInfo_FloatList.Size(m)
}
func (m *FloatList) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatList.DiscardUnknown(m)
}

var xxx_messageInfo_FloatList proto.InternalMessageInfo

func (m *FloatList) GetValue() []float32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type Int64List struct {
	Value                []int64  `protobuf:"varint,1,rep,packed,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64List) Reset()         { *m = Int64List{} }
func (m *Int64List) String() string { return proto.CompactTextString(m) }
func (*Int64List) ProtoMessage()    {}
func (*Int64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{2}
}
func (m *Int64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64List.Unmarshal(m, b)
}
func (m *Int64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64List.Marshal(b, m, deterministic)
}
func (dst *Int64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64List.Merge(dst, src)
}
func (m *Int64List) XXX_Size() int {
	return xxx_messageInfo_Int64List.Size(m)
}
func (m *Int64List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64List.DiscardUnknown(m)
}

var xxx_messageInfo_Int64List proto.InternalMessageInfo

func (m *Int64List) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

// Containers for non-sequential data.
type Feature struct {
	// Each feature can be exactly one kind.
	//
	// Types that are valid to be assigned to Kind:
	//	*Feature_BytesList
	//	*Feature_FloatList
	//	*Feature_Int64List
	Kind                 isFeature_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{3}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

type isFeature_Kind interface {
	isFeature_Kind()
}

type Feature_BytesList struct {
	BytesList *BytesList `protobuf:"bytes,1,opt,name=bytes_list,json=bytesList,oneof"`
}
type Feature_FloatList struct {
	FloatList *FloatList `protobuf:"bytes,2,opt,name=float_list,json=floatList,oneof"`
}
type Feature_Int64List struct {
	Int64List *Int64List `protobuf:"bytes,3,opt,name=int64_list,json=int64List,oneof"`
}

func (*Feature_BytesList) isFeature_Kind() {}
func (*Feature_FloatList) isFeature_Kind() {}
func (*Feature_Int64List) isFeature_Kind() {}

func (m *Feature) GetKind() isFeature_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Feature) GetBytesList() *BytesList {
	if x, ok := m.GetKind().(*Feature_BytesList); ok {
		return x.BytesList
	}
	return nil
}

func (m *Feature) GetFloatList() *FloatList {
	if x, ok := m.GetKind().(*Feature_FloatList); ok {
		return x.FloatList
	}
	return nil
}

func (m *Feature) GetInt64List() *Int64List {
	if x, ok := m.GetKind().(*Feature_Int64List); ok {
		return x.Int64List
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Feature) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Feature_OneofMarshaler, _Feature_OneofUnmarshaler, _Feature_OneofSizer, []interface{}{
		(*Feature_BytesList)(nil),
		(*Feature_FloatList)(nil),
		(*Feature_Int64List)(nil),
	}
}

func _Feature_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Feature)
	// kind
	switch x := m.Kind.(type) {
	case *Feature_BytesList:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BytesList); err != nil {
			return err
		}
	case *Feature_FloatList:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FloatList); err != nil {
			return err
		}
	case *Feature_Int64List:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Int64List); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Feature.Kind has unexpected type %T", x)
	}
	return nil
}

func _Feature_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Feature)
	switch tag {
	case 1: // kind.bytes_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BytesList)
		err := b.DecodeMessage(msg)
		m.Kind = &Feature_BytesList{msg}
		return true, err
	case 2: // kind.float_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FloatList)
		err := b.DecodeMessage(msg)
		m.Kind = &Feature_FloatList{msg}
		return true, err
	case 3: // kind.int64_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Int64List)
		err := b.DecodeMessage(msg)
		m.Kind = &Feature_Int64List{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Feature_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Feature)
	// kind
	switch x := m.Kind.(type) {
	case *Feature_BytesList:
		s := proto.Size(x.BytesList)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Feature_FloatList:
		s := proto.Size(x.FloatList)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Feature_Int64List:
		s := proto.Size(x.Int64List)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Features struct {
	// Map from feature name to feature.
	Feature              map[string]*Feature `protobuf:"bytes,1,rep,name=feature" json:"feature,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Features) Reset()         { *m = Features{} }
func (m *Features) String() string { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()    {}
func (*Features) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{4}
}
func (m *Features) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features.Unmarshal(m, b)
}
func (m *Features) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features.Marshal(b, m, deterministic)
}
func (dst *Features) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features.Merge(dst, src)
}
func (m *Features) XXX_Size() int {
	return xxx_messageInfo_Features.Size(m)
}
func (m *Features) XXX_DiscardUnknown() {
	xxx_messageInfo_Features.DiscardUnknown(m)
}

var xxx_messageInfo_Features proto.InternalMessageInfo

func (m *Features) GetFeature() map[string]*Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

// Containers for sequential data.
//
// A FeatureList contains lists of Features.  These may hold zero or more
// Feature values.
//
// FeatureLists are organized into categories by name.  The FeatureLists message
// contains the mapping from name to FeatureList.
//
type FeatureList struct {
	Feature              []*Feature `protobuf:"bytes,1,rep,name=feature" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FeatureList) Reset()         { *m = FeatureList{} }
func (m *FeatureList) String() string { return proto.CompactTextString(m) }
func (*FeatureList) ProtoMessage()    {}
func (*FeatureList) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{5}
}
func (m *FeatureList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureList.Unmarshal(m, b)
}
func (m *FeatureList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureList.Marshal(b, m, deterministic)
}
func (dst *FeatureList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureList.Merge(dst, src)
}
func (m *FeatureList) XXX_Size() int {
	return xxx_messageInfo_FeatureList.Size(m)
}
func (m *FeatureList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureList.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureList proto.InternalMessageInfo

func (m *FeatureList) GetFeature() []*Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type FeatureLists struct {
	// Map from feature name to feature list.
	FeatureList          map[string]*FeatureList `protobuf:"bytes,1,rep,name=feature_list,json=featureList" json:"feature_list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FeatureLists) Reset()         { *m = FeatureLists{} }
func (m *FeatureLists) String() string { return proto.CompactTextString(m) }
func (*FeatureLists) ProtoMessage()    {}
func (*FeatureLists) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{6}
}
func (m *FeatureLists) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureLists.Unmarshal(m, b)
}
func (m *FeatureLists) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureLists.Marshal(b, m, deterministic)
}
func (dst *FeatureLists) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureLists.Merge(dst, src)
}
func (m *FeatureLists) XXX_Size() int {
	return xxx_messageInfo_FeatureLists.Size(m)
}
func (m *FeatureLists) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureLists.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureLists proto.InternalMessageInfo

func (m *FeatureLists) GetFeatureList() map[string]*FeatureList {
	if m != nil {
		return m.FeatureList
	}
	return nil
}

type Sample struct {
	Features             *Features `protobuf:"bytes,1,opt,name=features" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{7}
}
func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (dst *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(dst, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetFeatures() *Features {
	if m != nil {
		return m.Features
	}
	return nil
}

type SampleList struct {
	Model                []*Sample `protobuf:"bytes,1,rep,name=model" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SampleList) Reset()         { *m = SampleList{} }
func (m *SampleList) String() string { return proto.CompactTextString(m) }
func (*SampleList) ProtoMessage()    {}
func (*SampleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{8}
}
func (m *SampleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleList.Unmarshal(m, b)
}
func (m *SampleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleList.Marshal(b, m, deterministic)
}
func (dst *SampleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleList.Merge(dst, src)
}
func (m *SampleList) XXX_Size() int {
	return xxx_messageInfo_SampleList.Size(m)
}
func (m *SampleList) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleList.DiscardUnknown(m)
}

var xxx_messageInfo_SampleList proto.InternalMessageInfo

func (m *SampleList) GetModel() []*Sample {
	if m != nil {
		return m.Model
	}
	return nil
}

type SequenceSample struct {
	Context              *Features     `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	FeatureLists         *FeatureLists `protobuf:"bytes,2,opt,name=feature_lists,json=featureLists" json:"feature_lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SequenceSample) Reset()         { *m = SequenceSample{} }
func (m *SequenceSample) String() string { return proto.CompactTextString(m) }
func (*SequenceSample) ProtoMessage()    {}
func (*SequenceSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_feature_9903592f1927532a, []int{9}
}
func (m *SequenceSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceSample.Unmarshal(m, b)
}
func (m *SequenceSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceSample.Marshal(b, m, deterministic)
}
func (dst *SequenceSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceSample.Merge(dst, src)
}
func (m *SequenceSample) XXX_Size() int {
	return xxx_messageInfo_SequenceSample.Size(m)
}
func (m *SequenceSample) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceSample.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceSample proto.InternalMessageInfo

func (m *SequenceSample) GetContext() *Features {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *SequenceSample) GetFeatureLists() *FeatureLists {
	if m != nil {
		return m.FeatureLists
	}
	return nil
}

func init() {
	proto.RegisterType((*BytesList)(nil), "stormtf.BytesList")
	proto.RegisterType((*FloatList)(nil), "stormtf.FloatList")
	proto.RegisterType((*Int64List)(nil), "stormtf.Int64List")
	proto.RegisterType((*Feature)(nil), "stormtf.Feature")
	proto.RegisterType((*Features)(nil), "stormtf.Features")
	proto.RegisterMapType((map[string]*Feature)(nil), "stormtf.Features.FeatureEntry")
	proto.RegisterType((*FeatureList)(nil), "stormtf.FeatureList")
	proto.RegisterType((*FeatureLists)(nil), "stormtf.FeatureLists")
	proto.RegisterMapType((map[string]*FeatureList)(nil), "stormtf.FeatureLists.FeatureListEntry")
	proto.RegisterType((*Sample)(nil), "stormtf.Sample")
	proto.RegisterType((*SampleList)(nil), "stormtf.SampleList")
	proto.RegisterType((*SequenceSample)(nil), "stormtf.SequenceSample")
}

func init() { proto.RegisterFile("feature.proto", fileDescriptor_feature_9903592f1927532a) }

var fileDescriptor_feature_9903592f1927532a = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcf, 0xae, 0xd2, 0x40,
	0x18, 0xc5, 0x9d, 0x56, 0x28, 0xfd, 0x5a, 0xb5, 0x4e, 0x30, 0x21, 0x2c, 0x0c, 0x36, 0x81, 0x10,
	0x8c, 0x2c, 0xa8, 0x51, 0x64, 0x49, 0x22, 0x91, 0x84, 0x55, 0x71, 0x6f, 0x0a, 0x4c, 0x93, 0x86,
	0xd2, 0x62, 0x67, 0x30, 0xf6, 0x35, 0x7c, 0x11, 0xef, 0x23, 0xde, 0xcc, 0x9f, 0x0e, 0xbd, 0x85,
	0xbb, 0xeb, 0xcc, 0xfc, 0xce, 0x7c, 0xe7, 0x1c, 0x18, 0x78, 0x15, 0x93, 0x88, 0x5d, 0x0a, 0x32,
	0x3d, 0x17, 0x39, 0xcb, 0xb1, 0x45, 0x59, 0x5e, 0x9c, 0x58, 0xec, 0x7f, 0x00, 0x7b, 0x59, 0x32,
	0x42, 0x37, 0x09, 0x65, 0xb8, 0x0b, 0xad, 0x3f, 0x51, 0x7a, 0x21, 0x3d, 0x34, 0x30, 0xc7, 0x6e,
	0x28, 0x17, 0xfe, 0x10, 0xec, 0x55, 0x9a, 0x47, 0x4c, 0x20, 0xbd, 0x3a, 0x62, 0x2c, 0x0d, 0x0f,
	0xd5, 0xb0, 0x75, 0xc6, 0xbe, 0x7c, 0xbe, 0xc5, 0xcc, 0x3a, 0xf6, 0x80, 0xc0, 0x5a, 0x49, 0x2f,
	0x38, 0x00, 0xd8, 0xf1, 0xe1, 0xbf, 0xd2, 0x84, 0xb2, 0x1e, 0x1a, 0xa0, 0xb1, 0x33, 0xc3, 0x53,
	0x65, 0x6d, 0xaa, 0x7d, 0xfd, 0x78, 0x11, 0xda, 0x3b, 0x6d, 0x32, 0x00, 0x88, 0xb9, 0x1d, 0x29,
	0x32, 0x1a, 0x22, 0xed, 0x94, 0x8b, 0x62, 0x6d, 0x3b, 0x00, 0x48, 0xb8, 0x39, 0x29, 0x32, 0x1b,
	0x22, 0xed, 0x9b, 0x8b, 0x92, 0x6a, 0xb1, 0x6c, 0xc3, 0xcb, 0x63, 0x92, 0x1d, 0xfc, 0x7f, 0x08,
	0x3a, 0xca, 0x32, 0xc5, 0x73, 0xb0, 0x54, 0x95, 0x22, 0x9b, 0x33, 0x7b, 0x7f, 0x9d, 0xad, 0x98,
	0xea, 0xe3, 0x7b, 0xc6, 0x8a, 0x32, 0xac, 0xf0, 0xfe, 0x06, 0xdc, 0xfa, 0x01, 0xf6, 0xc0, 0x3c,
	0x92, 0x52, 0xc4, 0xb6, 0x43, 0xfe, 0x89, 0x47, 0x55, 0x6b, 0x32, 0x95, 0xd7, 0xbc, 0x59, 0x75,
	0xb8, 0x30, 0xe6, 0xc8, 0xff, 0x06, 0x8e, 0xda, 0x15, 0x01, 0x27, 0x4d, 0x5b, 0xb7, 0xe2, 0x0a,
	0xf0, 0xff, 0x23, 0xed, 0x84, 0x6b, 0x29, 0x5e, 0x83, 0xab, 0xce, 0xaa, 0x5f, 0x82, 0xdf, 0x30,
	0x6a, 0xde, 0x20, 0xe0, 0xfa, 0x42, 0x06, 0x74, 0xe2, 0xeb, 0x4e, 0xff, 0x27, 0x78, 0x4d, 0xe0,
	0x4e, 0xd0, 0xc9, 0xd3, 0xa0, 0xdd, 0x7b, 0x93, 0xea, 0x61, 0xbf, 0x42, 0x7b, 0x1b, 0x9d, 0xce,
	0x29, 0xc1, 0x9f, 0xa0, 0xa3, 0xc6, 0x51, 0xf5, 0x87, 0x79, 0x7b, 0xd3, 0x7f, 0xa8, 0x11, 0x3f,
	0x00, 0x90, 0x42, 0x51, 0xd2, 0x10, 0x5a, 0xa7, 0xfc, 0x40, 0x52, 0x15, 0xf0, 0x8d, 0x56, 0x4a,
	0x26, 0x94, 0xa7, 0x7e, 0x09, 0xaf, 0xb7, 0xe4, 0xf7, 0x85, 0x64, 0x7b, 0xa2, 0xa6, 0x7e, 0x04,
	0x6b, 0x9f, 0x67, 0x8c, 0xfc, 0x65, 0xcf, 0x0f, 0xad, 0x08, 0xbc, 0xd0, 0x8f, 0x4d, 0xb4, 0x49,
	0x55, 0xc8, 0x77, 0x77, 0xeb, 0x0c, 0xdd, 0x5a, 0x7b, 0x74, 0xd7, 0x16, 0xcf, 0x33, 0x78, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0xf0, 0x57, 0x5f, 0x7f, 0xaf, 0x03, 0x00, 0x00,
}
